name: Lint code
on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_php_files:
    runs-on: ubuntu-latest
    outputs:
      php_changed: ${{ steps.check_file_changed.outputs.php_file_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - shell: pwsh
      id: check_php_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '.php$' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docs_changed"
        Write-Host "::set-output name=php_file_changed::$HasDiff"
  lint:
    runs-on: ubuntu-latest
    needs: [ check_php_files ]
    if: needs.check_php_files.outputs.php_file_changed == 'True'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0      
      - run: |
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer require nunomaduro/phpinsights --dev
          php vendor/bin/phpinsights --version
          php vendor/bin/phpinsights analyse --no-interaction --format=github-action \
          --min-style=100 --min-architecture=100 --min-quality=100
